export const CONSOLE_METHODS = {
  assert: "assert",
  clear: "clear",
  count: "count",
  countReset: "countReset",
  debug: "debug",
  dir: "dir",
  dirxml: "dirxml",
  error: "error",
  group: "group",
  groupCollapsed: "groupCollapsed",
  groupEnd: "groupEnd",
  info: "info",
  log: "log",
  profile: "profile",
  profileEnd: "profileEnd",
  table: "table",
  time: "time",
  timeLog: "timeLog",
  timeEnd: "timeEnd",
  timeStamp: "timeStamp",
  trace: "trace",
  warn: "warn"
};